### ISSUE TITLE
About the option 'eliminate_duplicate'

### ISSUE THREAD

**Issue by rqhu1995** [msu-coinlab/pymoo#103]
First of all, thanks for your systematic work!  I am currently working on an optimization problem with integer variables using pymoo, and here I have some problems. The algorithm I focus on is MOEA/D. 

The first problem is that I don't quite understand the difference between `sampling=get_sampling("int_random")` as the parameter of the constructor of `MOEAD` and the parameter for the parameter `type_var=np.int` as the parameter of the customized problem. I tried both of them and found that the solutions generated only using `type_var=np.int` were still float values (I used `print(res.X)` to check this). However, using `sampling=get_sampling("int_random")` worked quite fine. I would appreciate it if some explanation on this would be provided.
 
Another problem occurred with the option `eliminate_duplicates`. I noticed that `sampling=get_sampling("int_random")` first generate float values and at last convert float values as integers. After this, the elimination of the duplicate individuals was conducted, making the number of samples less than the initial `pop_size`. Say I am using "das-dennis" to generate ref_dir with 2 objectives and n_partitions is 14, then I would get 15 ref_dirs. Theoretically, setting pop_size of 15 would be enough when selecting two random individuals according to the distance of ref_dirs. However, as some duplicate individuals are removed, errors would show up as not able to index when doing `FV = self._decomposition.do(pop[N].get("F"), weights=self.ref_dirs[N, :], ideal_point=self.ideal_point)` in `pop[N].get("F")`, as `N` contains indices removed because of duplication in `pop`.

As far as I am concerned, the elimination should be done but the size of the population should be kept, i.e. the sampling should stop only if non-duplicate individuals of the pop_size are generated rather than loss of the size of the individuals.

Thanks.

**Comment by julesy89** [comment]
I have added the `type_var` more or less as a hint if you design your own algorithm. Because some algorithms have been designed and proposed for `float` you will have to customize them by yourself (as you are already intending to do) to work for other variables types. For the standard algorithms in our framework, `type_var` is not being used.

You have a good point. If you search space is rather small this can happen for integer problems. I think the cleanest way is to put the eliminate duplicate logic in the `Sampling` itself and repeat it until enough unique individual have been sampled. I have done the same in `Mating` because there it is more likely to be of an issue. 

Can you send a pull request with your solution?

Thanks,
Julian
