### ISSUE TITLE
converting result to json 

### ISSUE THREAD

**Issue by farmboy-dev** [msu-coinlab/pymoo#106]
Hi , I'm trying to convert res object to json using jsonify() 

but there was error, because jsonify was not able to control some classes. 

![image](https://user-images.githubusercontent.com/70833564/96092726-38acc800-0f06-11eb-8d97-99ec5d60499e.png)

Is there any method? 

Thank you in advance.

**Comment by julesy89** [comment]
The algorithm object can not be easily stored as JSON.


a) You can try to set `res.algorithm=None` and see if this works.

b) Otherwise, just create a dict to jsonify:

```
my_res = dict(X=res.X, F=res.F)
```

Of course you can add even more attributes.

c) If you are just interested in the optimum, you can also store `res.opt`.


More information about the result objective are available here:
https://pymoo.org/interface/result.html

**Comment by farmboy-dev** [comment]
Thank you 

I chose (b)
