### ISSUE TITLE
How to pass parameters to cost function in functional definition of Problem?

### ISSUE THREAD

**Issue by Antonio-Nappi** [msu-coinlab/pymoo#117]
Hi everybody, I'm newbie in pymoo so my question could sound stupid. I want  to pass some parameters used in the cost function, how can I do it with the problem definition with the functional method?

**Comment by julesy89** [comment]
You have to elaborate a bit more on what you intend to do. Most likely, your question is more related to Python and object-oriented programming itself rather than about pymoo. To get started, please also have a look at our getting started guide.
https://pymoo.org/getting_started.html

**Comment by xshang93** [comment]
Just came across this one and I think I'm having the same issue. To elaborate:
Say my objective functions are defined separately as:
```
def g1(x):
    <some expression>
    return y1
def g2(x):
    <some expression>
    return y2
```

Then, when I try to define the problem using
`obj=[g1(solution),g2(solution)]`
Obviously the current solution being evaluated should be passed as the input argument for g1 and g2, but since they are not defined anywhere, the interpreter will yield error. In the tutorial the lambda function was used to define the functions and that is fine, but not for customised functions.

So, what is the proper way to define the problem?

TIA

**Comment by blankjul** [comment]
yes I think you already answered the question yourself. You can do it even shorter:

```
obj=[g1, g2]
```

**Comment by xshang93** [comment]
> yes I think you already answered the question yourself. You can do it even shorter:
> 
> ```
> obj=[g1, g2]
> ```

Right. Thanks for the reply. This is indeed a python-related question.
