### ISSUE TITLE
Incorrect default parameter value in Riesz energy reference direction?

### ISSUE THREAD

**Issue by BenCrulis** [msu-coinlab/pymoo#134]
Hello everyone.
In the class RieszEnergyReferenceDirectionFactory, it is said that a good value for `d` is the number of dimensions squared:
https://github.com/msu-coinlab/pymoo/blob/567901c0681081e7e928ccc51c0ec6c7a3e32edd/pymoo/util/ref_dirs/energy.py#L49

However the actual computation for `d` is multiplying the number of dimensions by two:
https://github.com/msu-coinlab/pymoo/blob/567901c0681081e7e928ccc51c0ec6c7a3e32edd/pymoo/util/ref_dirs/energy.py#L51
According to the comment it should be
```python
self.d = n_dim ** 2
```

Is that a mistake in the comment or in the code?

**Comment by julesy89** [comment]
Not really a typo, but we have realized the square has issues in larger dimensions because of precision issues.
Because for 10 dimensions, a number is taken to the power of 100 already. For smaller dimensions that is not a problem though. 

Please let me know if your experiments show a better recommendation for `d`.

We provide some empirical results in the supplementary material of the paper: 
https://ieeexplore.ieee.org/ielx7/4235/9340033/9086772/supp1-2992387.pdf?tp=&arnumber=9086772

**Comment by BenCrulis** [comment]
I suggest updating the comment to avoid future confusion if someone look at the code.

I read this while I was investigating unusually very long computation times when generating 10 000 reference directions, but that's another issue. I will investigate and open another github issue if necessary, unless maybe both issues are linked somehow.

**Comment by julesy89** [comment]
Yes, thanks for letting me know.

Since most MOEAs use not more than 1000 reference directions (keep in mind this is often equal to your population size) scaling the number of reference directions played only a minor role in our study.

**Comment by BenCrulis** [comment]
I am generating this much reference directions because I use them to get points on the true Pareto front on some problems. According to a recent paper, IGD+ works better with something like 10 000+ points.

When generating reference directions for heuristics like NSGA-III, I am indeed generating as much points as the population size setting, ~200 individuals and everything works well and fast in this case.
