### ISSUE TITLE
question related to constraint 

### ISSUE THREAD

**Issue by hfahad** [msu-coinlab/pymoo#175]
Hii,
Very nice work, but i am struggling in one point that if we have a problem like:
y1 = f1(x1,x2,x3,...)
y2 = f2(x1,x2,x3,...)
and the constraint i want to apply is like
g : y2>10

which means the function should be greater then 10 and ignore the bellow 10 values.

but this problem is not working, what should I do to solve this problem

best,
Hafiz

**Comment by JiQi535** [comment]
> Hii,
> Very nice work, but i am struggling in one point that if we have a problem like:
> y1 = f1(x1,x2,x3,...)
> y2 = f2(x1,x2,x3,...)
> and the constraint i want to apply is like
> g : y2>10
> 
> which means the function should be greater then 10 and ignore the bellow 10 values.
> 
> but this problem is not working, what should I do to solve this problem
> 
> best,
> Hafiz

Hi Hafiz, if I understand your question correctly, your constraint of `y2>10` is equivalent to `10-y2<0`. In this way, you can define your "G" as `10-y2`. I learned this logic from the [pymoo starting guide](https://pymoo.org/getting_started.html), the "Implementation of a Problem" part to be exact.

**Comment by hfahad** [comment]
Hi, thanks for reply.
i already tried this way but its not working. i checked in the guidelines the mentioned if you have a > constraint not < less, you have tomultiply with " - " I did both ways but still I got bellow 10 values of y2 in the preto optimal solutions.

**Comment by JiQi535** [comment]
> Hi, thanks for reply.
> i already tried this way but its not working. i checked in the guidelines the mentioned if you have a > constraint not < less, you have tomultiply with " - " I did both ways but still I got bellow 10 values of y2 in the preto optimal solutions.

I think there is no guarantee by pymoo to find feasible solutions that obey all constraints.  So that's why we need to evaluate things like constraint violations. Some constraints you set can be too strict. 

For example, if I want to buy a car with two constraints, 1. milage below 20k mile; 2. cost less than 2k dollars, it would be almost impossible to find a car like this, even if I define my constraints in a correct way. So I guess in your case, either the constraint is too strict, or the optimization iterations are not sufficient.

**Comment by hfahad** [comment]
Thanks for your help and suggestions,
