### ISSUE TITLE
How do you handle equality constraints?

### ISSUE THREAD

**Issue by leytzher** [msu-coinlab/pymoo#19]
Thanks for this great library.
I am wondering if it is possible to handle equality constraints and how to do it in pymoo.
For example, if we want the sum of x <= 500 we do: 
```g1 = anp.sum(x ,axis=1) - 500```
How can we do if we want the sum of x = 500?
Thanks/

**Comment by julesy89** [comment]
Equality Constraints are in general challenging to handle using Genetic Algorithms. One way of handling them is see it as a small range.

Assuming:
g(x): x = 5


Other options of coding it:
g'(x): |x -5| <= 0   or almost the same g''(x): (x-5)^2 <= 0 

But since the constraint is so strict introducing an epsilon is applied in practice:
g'''(x): (x-5)^2  - eps <= 0
 4.999 <= x <= 5.001  (this can be formulated as two inequality constraints)


However, all of that is possible I highly recommend using a repair operator. 
Those constraints make most of the search space infeasible which makes it difficult for the algorithm to converge to a feasible region. 

An example for a Knapsack Problem is provided below:

```
import numpy as np

from pymoo.factory import get_algorithm, get_crossover, get_mutation, get_sampling
from pymoo.model.repair import Repair
from pymoo.optimize import minimize
from pymoo.problems.single import create_random_knapsack_problem


class ConsiderMaximumWeightRepair(Repair):

    def _do(self, problem, pop, **kwargs):

        # maximum capacity for the problem
        Q = problem.C

        # the packing plan for the whole population (each row one individual)
        Z = pop.get("X")

        # the corresponding weight of each individual
        weights = (Z * problem.W).sum(axis=1)

        # now repair each indvidiual i
        for i in range(len(Z)):

            # the packing plan for i
            z = Z[i]

            # while the maximum capacity violation holds
            while weights[i] > Q:
                # randomly select an item currently picked
                item_to_remove = np.random.choice(np.where(z)[0])

                # and remove it
                z[item_to_remove] = False

                # adjust the weight
                weights[i] -= problem.W[item_to_remove]

        # set the design variables for the population
        pop.set("X", Z)
        return pop


method = get_algorithm("ga",
                       pop_size=200,
                       sampling=get_sampling("bin_random"),
                       crossover=get_crossover("bin_hux"),
                       mutation=get_mutation("bin_bitflip"),
                       repair=ConsiderMaximumWeightRepair(),
                       elimate_duplicates=True)

res = minimize(create_random_knapsack_problem(30),
               method,
               termination=('n_gen', 10),
               verbose=True)


```
Then, your search focuses to search in the feasible space which will increase the performance for most of the problems.

**Comment by leytzher** [comment]
@julesy89 Thank you for the detailed explanation!
