### ISSUE TITLE
Does it support multi processor?

### ISSUE THREAD

**Issue by TheSilverLinings** [msu-coinlab/pymoo#30]

**Comment by julesy89** [comment]
Yes it does!

a) Since most of the algorithms are population based you can write your own parallelization in the `_evaluate` function of your problem. This function takes a list of individuals to be evaluated where the list corresponds to the current population. The purpose of the function is to evaluate each of those and return the function values (and constraints). 
By implementing this function by yourself, you have total freedom in parallelization. 

b) Also, there is a built-in parallelization: https://pymoo.org/problems/parallelization.html
If this fulfills your needs you can simply use the examples provided in our documentation.

**Comment by JiQi535** [comment]
Dear Julian, 

I want to ask a follow-up question about parallelization. I followed the pymoo documentation for parallelization with `multiprocessing` and successfully parallelized my evaluations. However, from my test, **when trying to continue the `minimize `process from stored checkpoint, the parallelization does not work any more.**

I used normal settings to save the checkpoint to checkpoint.npy and loaded it. Everything else remains the same as the successfully parallelized version. I wonder if the minimization from a checkpoint can be parallelized. Thanks in advance!

**Comment by JiQi535** [comment]
> Yes it does!
> 
> a) Since most of the algorithms are population based you can write your own parallelization in the `_evaluate` function of your problem. This function takes a list of individuals to be evaluated where the list corresponds to the current population. The purpose of the function is to evaluate each of those and return the function values (and constraints).
> By implementing this function by yourself, you have total freedom in parallelization.
> 
> b) Also, there is a built-in parallelization: https://pymoo.org/problems/parallelization.html
> If this fulfills your needs you can simply use the examples provided in our documentation.

Dear Julian,

I want to ask a follow-up question about parallelization. I followed the pymoo documentation for parallelization with `multiprocessing` and successfully parallelized my evaluations. However, from my test, **when trying to continue the `minimize` process from stored checkpoint, the parallelization does not work any more.**

I used normal settings to save the checkpoint to checkpoint.npy and loaded it. Everything else remains the same as the successfully parallelized version. I wonder if the minimization from a checkpoint can be parallelized. Thanks in advance!

**Comment by julesy89** [comment]
At this point, the parallelization is disabled after loading from a checkpoint. The reason for that is the limitation of Python to serialize a thread or process pool. 

One workaround is that you can implement your own parallelization in your problem. After loading from the checkpoint, you set `algorithm.problem` to your implementation with an initialized thread or process pool.
