### ISSUE TITLE
Bug in PYMOO N-Dimensional Scatter Plot

### ISSUE THREAD

**Issue by kalyanpi4** [msu-coinlab/pymoo#37]
I was playing around with the n-dimensional scatter plot and possibly found a bug. Please see the image below:
![image](https://user-images.githubusercontent.com/60096376/72721524-49f8bc00-3ba2-11ea-88bc-c224731daffc.png)

It is expected that about the diagonal corresponding plots would be rotated. In fact all the plots look exactly the same.

Here's the random data I used (space separated):

0.50043 0.060429 0.737314 0.742259
0.14787 0.907006 0.394185 0.798932
0.953716 0.159536 0.034512 0.86805
0.200498 0.311165 0.617604 0.606972
0.928566 0.340058 0.397085 0.152281
0.888746 0.477383 0.531482 0.69961
0.878204 0.502142 0.710674 0.455302
0.328805 0.85086 0.834285 0.176581
0.397921 0.212607 0.32161 0.894788
0.199863 0.986696 0.635643 0.054622

**Comment by julesy89** [comment]
Thanks for reporting it! Yes, it is a bug for ND-Scatter plots.

In scatter.py the line 

`self.plot(ax, _type, F, **_kwargs)`

needs to be changed to 

`self.plot(ax, _type, F[:, [i, j]], **_kwargs)`

It will be fixed in the next release of pymoo.

Until then copy this file to your local project and use it for plotting: 
https://www.egr.msu.edu/coinlab/blankjul/scatter.py

Please let me know if this works for you.
And thanks for reporting your concern. We like to improve pymoo more and more
and this helps us to get it as bug free as possible.
