### ISSUE TITLE
How to print custom output. In the subset problem

### ISSUE THREAD

**Issue by wd1969** [msu-coinlab/pymoo#43]
How to print custom output. In the subset problem, there are hundreds of possible variables. I want to track the number of variables that are not selected for evaluation and use them to adjust mutation parameters. For example, calculate x.sum (0) in the _evaluate function and add the parameter column to the print list.

**Comment by julesy89** [comment]
I have developed a new print module which I am going to finalize soon.
Currently, you can simply use the callback function.

https://pymoo.org/misc/callback.html

You have access to the current population through in algorithm object.

For the subset selection problem in the documentation printing the minimum and maximum number of not selected entries would look like the following:
(Even though here it does not make sense because always 10 are selected which is ensured by the constraint)

```
def my_callback(algorithm):
    disp = algorithm.func_display_attrs(algorithm.problem, algorithm.evaluator, algorithm, algorithm.pf)
    not_selected = (~algorithm.pop.get("X")).sum(axis=1)
    print("Not Selected: (%s, %s) | " % (not_selected.min(), not_selected.max()), end='')
    algorithm._display(disp)


algorithm = GA(
    pop_size=100,
    sampling=MySampling(),
    crossover=BinaryCrossover(),
    mutation=MyMutation(),
    eliminate_duplicates=True,
    callback=my_callback)

res = minimize(problem,
               algorithm,
               ('n_gen', 60),
               seed=1,
               verbose=False)
```
