### ISSUE TITLE
how to visualize data from nsga2 algorithm

### ISSUE THREAD

**Issue by karmab** [msu-coinlab/pymoo#60]
from pymoo documentation, in https://www.pymoo.org/getting_started.html#Optimize
the output table contains the following parameters:

- cv (min) 
- cv (avg)
- igd
- gd
- hv

Can you explain what cv(min) and cv(avg) mean?
I've run the same example and i get different output

```
====================================================================================================
n_gen |  n_eval |   cv (min)   |   cv (avg)   |  n_nds  | delta_ideal  | delta_nadir  |   delta_f   
====================================================================================================
    1 |      10 |  5.752159627 |  2.95357E+01 |       1 |            - |            - |            -
    2 |      20 |  0.00000E+00 |  6.428008389 |       1 |  1.018896179 |  1.018896179 |  1.02232E+30
    3 |      30 |  0.00000E+00 |  3.680333713 |       1 |  0.00000E+00 |  0.00000E+00 |  0.00000E+00
```

**Comment by julesy89** [comment]
Good point. I probably should add an explanation for that somewhere in the documentation.
Where in our software documentation at pymoo.org would you have looked at to find some more details about the printouts? I am asking because this is where I would add my answer below.

**cv(min):** The solution with the minimum constraint violation found so far.
**cv(avg):** The average constraint violation of the current population (makes only really sense for genetic algorithms)
**n_nds:** Number of non-dominated solutions in the current population

The last three printouts are based on metrics and solutions known to be important for multi-objective optimization. We have recently written a paper which will be available soon that explains those metrics and how they are used to decide if the algorithm terminates or not.

**delta_ideal:** Normalized movement of the ideal point from the last to the current population
**delta_nadir:** Normalized movement of the nadir point from the last to the current population
**delta_f:** The overall movement of non-dominated solutions from one generation by another (IGD) normalized with respect to the current population.

**Comment by karmab** [comment]
i never got back at you, but thanks for the quick reply!!!
i think the getting started was a good place for the content.
