### ISSUE TITLE
Travis build failed for unknown reason

### ISSUE THREAD

**Issue by Peng-YM** [msu-coinlab/pymoo#67]
The Travis test failed on my `pymoo` forked repository. The output is shown below:
![Travis Output](https://user-images.githubusercontent.com/21050064/82882642-f04f3680-9f73-11ea-9b15-ad102f1de8f4.png)
It seems that the unittest `test_problem` wants to examine `__pycache__` which does not exist in my repository (since it is on the .gitignore file). Could you help me to resolve this issue? The link to my forked repository is [here](https://github.com/Peng-YM/pymoo). Thank you in advance :)

Best regard

**Comment by julesy89** [comment]
The reason seems to be a different one. The `test_usage` searches for all files (apparently also folder) in the usage folder.

replace the line in the *test_usage.py* by

`usages = [f for f in usages if (f != "__init__.py" or "__pycache__" in f)]`

and it should work. Your IDE creates this folder (did not happen for me yet).

**Comment by Peng-YM** [comment]
Thank you Julian, problem fixed!
