### ISSUE TITLE
Constraint Handling: implementation details

### ISSUE THREAD

**Issue by astha736** [msu-coinlab/pymoo#70]
Hi, 

Since the problem I am trying to solve is heavily dependent on constraint handling.  Therefore, 
I would like to know more about the implementation details for constraint handling in pymoo. 

I have already read through the  [constraint_handling ]( https://pymoo.org/misc/constraint_handling.html) page and it provided me with a very good starting point. But, I would like to know a few more things. For example, what happens when most of the solution ( 34 out of 36, especially at the start of the evolution) do not satisfy the constraint (g(x) <= 0). Are they considered for producing next generation's solution ? what is the criteria ?

Could you please let me know how the above situation is handled and where can I find its source code ?

Thank you!

Regards,
Astha

**Comment by julesy89** [comment]
In pymoo by default the parameter-less constraint handling approach is implemented. In fact, this happens in the `Survival` class which most genetic algorithms' survivals inherit from. This constraint handling technique is easy to implement because it follows the feasibility first principle. This implies feasible solutions are sorted by their objective value and infeasible ones by their constraint violation. If only a small fraction of the population is feasible, mostly the constraint violation determines what individuals survive.

However, for highly constrained problems this can also cause issues . For instance, it might cause converging only to the first feasible region found and not exploring long enough. Especially if most of the search space is infeasible and many feasible rather small islands exist.

If you are interested in algorithm development I would be more than happy to see a pull request about constraint handling. The G function suite was developed to test constraint handling methods and is available too.

More Details about the Parameter-less Approach:
A Niched-Penalty Approach for Constraint Handling in Genetic Algorithms
https://link.springer.com/chapter/10.1007/978-3-7091-6384-9_40
