### ISSUE TITLE
moead algorithm problem evaluation

### ISSUE THREAD

**Issue by hyumo** [msu-coinlab/pymoo#76]
I am implementing parallel problem evaluation using a queuing system assuming that `X` is a matrix, each `x in X` is sent to a queue, with `elementwise_evaluation` set to `False`. 

However, it seems that when `moead` algorithm is used, population `X` is always a vector (1 row matrix) instead of a matrix, which prevents parallel evaluation. I checked the source code a bit, it seems (not tested) to be caused by https://github.com/msu-coinlab/pymoo/blob/6679c9c89648deb468790022dc5d8691fb7bf82b/pymoo/algorithms/moead.py#L91

I am not sure if this is intentional or not, correct me if I am wrong. Thank you.

**Comment by julesy89** [comment]
Yes that is correct. But that is because MOEAD does not evaluate the population as a whole but uses a for loop. This is simply as the algorithm was proposed. Changing that (and I have tried even though it deviates from the paper) also changes the performance of the algorithm. The for loop implementation makes the algorithm being more greedy because during the loop the evaluation of a single individual is already known.

**Comment by hyumo** [comment]
Thanks for your respond, that's very informative. I will try some other algorithms then. `moead` does give better performance tho, given the same computation resources.
