### ISSUE TITLE
__str__ called on Problem object initialization

### ISSUE THREAD

**Issue by aaronshifman** [msu-coinlab/pymoo#88]
Hello,

I've just started working with pymoo (It's great - kudos). 

I'm on python3.7.7 on windows 10 with pymoo 0.4.1

In this example

```python
from pymoo.model.problem import Problem
class TestProblem(Problem):
    def __str__(self):
        print('This is called')

a = TestProblem()
```

for some reason ``__str__`` is called on object creation. This is a problem because in [the parent class](https://github.com/msu-coinlab/pymoo/blob/master/pymoo/model/problem.py#L493-L501)  ``self.evaluate()`` gets called and the call stack is such that my debugger isn't able to catch the breakpoint (I made a mistake in my _evaluate code that was causing a crash but I couldn't investigate because I couldn't debug it)... I don't actually know where or why ``__str__`` is being called from.

I have a sneaking suspicion it's being called from another thread because if I place a breakpoint after ``TestProblem()`` then there's a short delay and the my buggy code would cause a crash. I have an intermediate workaround which is just overwriting the ``__str__`` but that's not the most elegant and without that debugging simulation code is a challenge

**Comment by julesy89** [comment]
Thanks for you feedback. I have removed the `evaluate` calls in the `__str__` method (in the current master branch) because they are not supposed to be there (I have added them when I have started the pymoo project a long time probably). 

I was able to reproduce the behavior in PyCharm and I can confirm the `__str__` is executed ONLY when debugged. 

Can you please check if the current master branch works for you? There, the statements shall be gone and make you life debugging easier (even though the `__str__` method will still be called).

If you find a way to avoid the call during debugging please let me and other know.
