### ISSUE TITLE
Regarding MOEAD

### ISSUE THREAD

**Issue by reyanrockz** [msu-coinlab/pymoo#9]
I didn't find the example of MOEAD in your documentation [https://www.egr.msu.edu/coinlab/blankjul/pymoo/](url)

Is MOEAD still in development?  If no can you provide an example of MOEAD?

**Comment by julesy89** [comment]
I finished coding up MOEAD. But so far did not benchmark it against other frameworks (NSGA-II and NSGA-III are well tested). Therefore, I did not put in the documentation yet.

However, here is the usage: https://github.com/msu-coinlab/pymoo/blob/master/pymoo/usage/moead.py

The implementation is based on C-code I used as a template (I think it was the original one which a lab mate got from the authors). However, I did not find the time for a benchmark.

As decomposition the default is using Tchebichew for 2 objectives and PBI for more or equal 3. 

Please let me know if you have feedback of any kind.

**Comment by reyanrockz** [comment]
Okay, Thanks for replying julesy89. I will run MOEAD on DTLZ1 and DTLZ2 and compare results with base paper results. Thanks Again.

**Comment by lureevnat** [comment]
Hii Julesy,

In the https://github.com/msu-coinlab/pymoo/blob/master/pymoo/cython/decomposition.py file, and in pbi function,
you wrote 
`d1 = np.sum((F - utopian_point) * weights, axis=1) / norm`

But I think below is correct
`d1 = np.linalg.norm((F - utopian_point) * weights, axis=1) / norm`

Please correct me if I wrong, I have referred Zhang, Qingfu, and Hui Li. "MOEA/D: A multiobjective evolutionary algorithm based on decomposition." IEEE Transactions on evolutionary computation 11.6 (2007): 712-731. before comenting.

**Comment by julesy89** [comment]
Thanks for the hint!

For the next release I am planning to recode the whole module. I will then double check all the equations. I have implemented it based on other source code (jMetal):

d1 = d2 = nl = 0.0;

      for (int i = 0; i < problem.getNumberOfObjectives(); i++) {
        d1 += (individual.getObjective(i) - idealPoint.getValue(i)) * lambda[i];
        nl += Math.pow(lambda[i], 2.0);
      }
      nl = Math.sqrt(nl);
      d1 = Math.abs(d1) / nl;

There, d1 its just the sum (the abs of d1 in the end is not necessary because the ideal point is the best point that can be achieved). However, I agree in the paper it is different.

**Comment by lureevnat** [comment]
Okay Julesy, Thanks for replying.

**Comment by julesy89** [comment]
Hey I just had one more look at the equation. And the implementation is correct (I saw the same implementation in several places). 

Basically, a dot product is applied which is done by multiplying and then taking the sum (simply the projection of a point onto a line). The outer norm in the denominator is not necessary (at least in my understanding) because the dot product already provides a scalar.

**Comment by lureevnat** [comment]
Okay Julesy. Thank you for replying.
