### ISSUE TITLE
[Feature request] Save non-dominated set for each generation

### ISSUE THREAD

**Issue by renatobellotti** [msu-coinlab/pymoo#91]
It would be nice to see how the non-dominated set improves over the generations.

So far, it seems that the non-dominated sert is just calculated at the very end of the algorithm. Calculating the hypervolume indicator is too expensive for high dimensional problems and/or many individuals and generations, but it would be very useful to see if the non-dominated set is still improving.

I suggest to add an attribute `nondominated_history` or something like this to the `Result` object. I assume the calculations are quite computationally expensive, so perhaps a flag `calculate_nondominated_each_gen` or similar would make sense for the `minimize()` function.

**Comment by renatobellotti** [comment]
I have checked in the NSGA-II code. The `NSGA2.opt` property contains all individuals of the current generation with rank 0. This means that it does not contain the non-dominated set up to and including the current generation.

Do you agree?

If yes, I suggest to add the `nondominated_history` property I proposed in my original post.

**Comment by julesy89** [comment]
For `NSGA2` this is true because it is domination-based. And yes you can use the `rank` attribute in this case.

Feel free to create a pull request (and an explanation that would have helped you in the getting started guide) and I will have a look over it. But bear in mind that non-dominated sorting is not being used for all algorithms. Decomposition-based algorithms work differently and non-dominated sorting will be only unnecessary overhead. 

To be honest I am not sure what you are intending to do. What is your overall goal? Keeping statistics? Extract all NDS solutions over the whole run?
If you intend to keep all non-dominated solutions (usually just called archiving), simply use an Archive that is filled in each generation in a `Callback` object. The archive does nothing else than merging the current Archive with `pop` and performs then NDS. However, the archive can grow quickly if only NDS is used.


```
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_problem
from pymoo.model.callback import Callback
from pymoo.model.population import Population
from pymoo.optimize import minimize
from pymoo.util.nds.non_dominated_sorting import NonDominatedSorting


class Archive:

    def __init__(self) -> None:
        super().__init__()
        self.nds = Population()

    def add(self, pop):
        merged = Population.merge(self.nds, pop)
        I = NonDominatedSorting().do(merged.get("F"), only_non_dominated_front=True)
        self.nds = merged[I]


class MyCallback(Callback):

    def __init__(self) -> None:
        super().__init__()
        self.archive = Archive()

    def notify(self, algorithm):
        self.archive.add(algorithm.pop)


problem = get_problem("zdt1")

algorithm = NSGA2(pop_size=100)

res = minimize(problem,
               algorithm,
               ('n_gen', 100),
               callback=MyCallback(),
               seed=1,
               verbose=False)

archive = res.algorithm.callback.archive.nds

print(len(archive))
```

Let me know if this is what you are intending to do.

And I agree this could be a tutorial in the documentation (maybe not the getting started guide though).

**Comment by renatobellotti** [comment]
Thanks for your detailed answer. I originally intended to see how the non-dominated set evolves over the generations, i. e. if and when it gets stationary. I underestimated how much memory the non-dominated sorting requires, so I will probably just stick to the final ones.

I hope I will find time to create a pull request, but I cannot promise it.
